import { ScanLine } from "lucide-react";
import { toast } from "sonner";

export default function PurchaseSerialEntry({
  itemIndex,
  field,
  watchedItem,
  register,
  setValue,
  getValues,
  handleQtyChange,
}) {
  const handleSerialInputKeyDown = (serialIndex, e) => {
    // Problem 2 Fix: intercept raw key codes context instantly to block global automatic native HTML form postings
    if (e.key === "Enter") {
      e.preventDefault();

      const currentRawValue = e.target.value;

      // Problem 2 & 4 Fix: Reject validation execution rules context if text values are purely empty space strings
      if (!currentRawValue || currentRawValue.toString().trim() === "") {
        toast.error(
          "Blank Space Rejection: Absolute white-space lines or faka inputs cannot be committed into database General Ledger records.",
        );
        setValue(`items.${itemIndex}.serials.${serialIndex}`, "");
        return;
      }

      const finalizedUpperToken = currentRawValue
        .toString()
        .trim()
        .toUpperCase();

      // Problem 3 Fix: Execute extensive cross-row global verification trace checks across entire data matrix arrays
      const allActiveFormRows = getValues("items") || [];
      let globalCollisionCount = 0;

      for (let rowIndex = 0; rowIndex < allActiveFormRows.length; rowIndex++) {
        const serialArrayLoop = allActiveFormRows[rowIndex]?.serials || [];
        for (let sPos = 0; sPos < serialArrayLoop.length; sPos++) {
          // Skip cell evaluation matching the identical pointer target running the processing logic loop matrix
          if (rowIndex === itemIndex && sPos === serialIndex) continue;

          if (
            serialArrayLoop[sPos] &&
            serialArrayLoop[sPos].toString().trim().toUpperCase() ===
              finalizedUpperToken
          ) {
            globalCollisionCount++;
          }
        }
      }

      if (globalCollisionCount > 0) {
        toast.error(
          `System Cross-Row Conflict: Identifier token key "${finalizedUpperToken}" has already been processed inside this purchase sheet template data grid entries.`,
        );
        setValue(`items.${itemIndex}.serials.${serialIndex}`, "");
        return;
      }

      // Update structural values safely to persist clean data records
      setValue(
        `items.${itemIndex}.serials.${serialIndex}`,
        finalizedUpperToken,
      );

      const computedTrackingSerialsArray =
        getValues(`items.${itemIndex}.serials`) || [];

      // If the inventory operator scans barcode on final field slot position, trigger automatic line increments setup
      if (serialIndex === computedTrackingSerialsArray.length - 1) {
        const activeInvoiceRowQty = parseInt(
          getValues(`items.${itemIndex}.qty`) || 0,
        );
        handleQtyChange(itemIndex, activeInvoiceRowQty + 1);

        // Problem 3 Fix: Run deferred focus updates matching dynamically newly mounted dynamic DOM element strings smoothly
        setTimeout(() => {
          const nextAutoGeneratedInputBox = document.getElementById(
            `serial-${itemIndex}-${serialIndex + 1}`,
          );
          if (nextAutoGeneratedInputBox) {
            nextAutoGeneratedInputBox.focus();
            nextAutoGeneratedInputBox.select();
          }
        }, 120);
      } else {
        // Shift cursor focus indexing metrics seamlessly into the neighboring adjacent cell context mapping
        setTimeout(() => {
          const simpleNextTargetBox = document.getElementById(
            `serial-${itemIndex}-${serialIndex + 1}`,
          );
          if (simpleNextTargetBox) {
            simpleNextTargetBox.focus();
            simpleNextTargetBox.select();
          }
        }, 60);
      }
    }
  };

  return (
    <tr className="bg-purple-50/10">
      <td colSpan={6} className="p-3 border-b border-gray-200">
        <div className="bg-white p-3 border border-purple-100 rounded-xl w-full">
          <div className="text-xs font-bold text-purple-800 mb-2 flex items-center gap-1 select-none">
            <ScanLine className="size-3.5 text-purple-600 animate-pulse" />
            Scan / Enter Unique Serial or IMEI Numbers for "{field.title}":
          </div>
          <div className="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-6 lg:grid-cols-10 gap-2 w-full">
            {(watchedItem?.serials || [""])?.map((serial, sIdx) => (
              <div key={sIdx} className="relative flex items-center h-8 w-full">
                <span className="absolute left-1.5 text-[9px] font-mono font-bold text-purple-500 bg-purple-50 px-1 rounded z-10 select-none scale-90">
                  #{sIdx + 1}
                </span>
                <input
                  id={`serial-${itemIndex}-${sIdx}`}
                  type="text"
                  autoComplete="off"
                  placeholder="Serial..."
                  className="w-full h-8 pl-7 pr-1 text-[11px] border border-purple-200 rounded focus:outline-none focus:ring-1 focus:ring-purple-400 focus:border-purple-600 font-mono uppercase font-bold text-purple-950 bg-purple-50/30"
                  {...register(`items.${itemIndex}.serials.${sIdx}`, {
                    required:
                      "Blank arrays are blocked under system validation mapping configurations.",
                  })}
                  onKeyDown={(e) => handleSerialInputKeyDown(sIdx, e)}
                />
              </div>
            ))}
          </div>
        </div>
      </td>
    </tr>
  );
}
